config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'welcome#index'
  
  #Cars controller
  get '/acheter-voiture-occasion', to: 'cars#acheter_voiture_occasion', as: 'acheter_voiture_occasion'  
  get '/vendre-voiture-occasion', to: 'cars#vendre_voiture_occasion', as: 'vendre_voiture_occasion'
  resources 'cars', :path => '/acheter-voiture-occasion'

  # Welcome controller
  get '/a-propos-de-nationale-7', to: 'welcome#a_propos_de_nationale_7', as: 'a_propos_de_nationale_7'
  get '/foire-aux-questions', to: 'welcome#foire_aux_questions', as: 'foire_aux_questions'
  get '/comment-ca-marche', to: 'welcome#comment_ca_marche', as: 'comment_ca_marche'
  get '/les-prix-nationale-7', to: 'welcome#les_prix_nationale_7', as: 'les_prix_nationale_7'
  get '/expertise-nationale-7', to: 'welcome#expertise_nationale_7', as: 'expertise_nationale_7'
  get '/conditions-generales-de-vente', to: 'welcome#conditions_generales_de_vente', as: 'conditions_generales_de_vente'
  get '/mentions-legales', to: 'welcome#mentions_legales', as: 'mentions_legales'


  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts
  match '/evaluations', to: 'evaluations#new', via: 'get'
  resources :evaluations


  resources 'acheteurs', :path => "/rechercher-voiture-occasion"
  resources 'sold', :path => "/voitures-occasion-vendues"
  resources 'annonces'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/nationale7v1/sitemaps/sitemap.xml.gz")

  #Footer routes
  get '/acheter-mini-occasion', to: 'cars#acheter_mini_occasion', as: 'acheter_mini_occasion'
  get '/acheter-diesel-occasion', to: 'cars#acheter_diesel_occasion', as: 'acheter_diesel_occasion'



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @cars = Car.where(statut: 'Actif').last(3).reverse
    @profile_photos = Photo.where(car_id: @cars.map(&:id)).where(description: 'Profile')
  end

  def comment_ca_marche

    prepare_meta_tags(
      title: "Tout savoir pour acheter et vendre",
      description: "Découvrir l'expérience Nationale 7 pour vendre sa voiture au meilleur prix et acheter sa voiture d'occasion, inspectée et garantie, en toute simplicité.",
      reverse: true
    )

    set_meta_tags og: {
      title: "Tout savoir sur l'expérience Nationale 7 pour acheter et vendre.",
      description: "Découvrir l'expérience Nationale 7 pour vendre sa voiture au meilleur prix et acheter sa voiture d'occasion, inspectée et garantie, en toute simplicité."
    }

  end

  def les_prix_nationale_7
    
    prepare_meta_tags(
      title: "Les prix N7, quand vendeurs et acheteurs sont gagnants !",
      description: "Les vendeurs obtiennent 20%\ de plus. Quant aux acheteurs, ils paient 10%\ de moins qu'en concession. Voici comment ça marche chez Nationale 7 !",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Un+meilleur+prix+pour+vendeurs+et+acheteurs+.png",
      reverse: true
    )

    set_meta_tags og: {
      title: "Les prix Nationale 7 : quand vendeurs et acheteurs sont gagnants !",
      description: "Les vendeurs obtiennent 20%\ de plus. Quant aux acheteurs, ils paient 10%\ de moins qu'en concession. Voici comment ça marche chez Nationale 7 !",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Un+meilleur+prix+pour+vendeurs+et+acheteurs+.png"
    }

  end

  def expertise_nationale_7
    
    prepare_meta_tags(
      title: "Expertise 75 points, obligatoire pour nos voitures",
      description: "Une heure pour inspecter votre voiture dans ses moindres détails : carrosserie, intérieur, mécanique, chassis, historique, entretien, test routier.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+expertise+75+points.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Expertise Nationale 7, 75 points : obligatoire pour toutes nos voitures.",
      description: "Une heure pour inspecter votre voiture dans ses moindres détails : carrosserie, intérieur, mécanique, chassis, historique, entretien, test routier.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+expertise+75+points.jpg"
    }

  end

  def a_propos_de_nationale_7
    
    prepare_meta_tags(
      title: "Une équipe en pleine croissance",
      description: "L'occasion l'esprit léger : nous facilitons la transaction de voitures d'occasion entre particuliers, pour que tout le monde y gagne.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+a+propos.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Nationale 7 : une équipe en pleine croissance, des rêves de voitures plein la tête.",
      description: "L'occasion l'esprit léger : nous facilitons la transaction de voitures d'occasion entre particuliers, pour que tout le monde y gagne.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+a+propos.jpg"
    }

  end

  def foire_aux_questions
    
    prepare_meta_tags(
      title: "Foire aux questions, foire aux réponses",
      description: "Les questions les plus souvent posées sur l'achat et la vente de voiture d'occasion avec Nationale 7.",
      reverse: true
    )

    set_meta_tags og: {
      title: "Nationale 7 - Foire aux questions, foire aux réponses",
      description: "Les questions les plus souvent posées sur l'achat et la vente de voiture d'occasion avec Nationale 7."
    }

  end

  def conditions_generales_de_vente
    
    prepare_meta_tags(
      title: "Conditions générales de vente",
      reverse: true
    )

  end

  def mentions_legales
    
    prepare_meta_tags(
      title: "Mentions légales",
      reverse: true
    )

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/expertise_nationale_7.html.erb
<header class="header-description-page">
  <div class="logo-product">
    <%= link_to image_tag('logo-blue.png'), root_path, class: "logo-product" %>
  </div>


  <ul class="menu align-right homepage-nav-bar"> 
    <li class="phone-number-header-product header-link-product"><a href="tel:0176390284" class="header-number-product">01 76 39 02 84</a></li>

    <li class="besoin-aide header-link-product"><a href="#aide-popup" class="open-popup-link menu-link-product sliding-middle-out sliding-blue">Besoin d'aide ?</a></li>  
    
    <li class="header-link-product"><%= link_to 'Vendre', vendre_voiture_occasion_path, class: "menu-link-product sliding-middle-out sliding-blue" %></li>  
    <li class="header-link-product"><%= link_to 'Acheter', acheter_voiture_occasion_path, class: "menu-link-product sliding-middle-out sliding-blue" %></li>
    <li class="header-link-product wrapper pourquoi-n7 sliding-blue">Pourquoi Nationale 7 ?
      <div class="sub-menu-homepage">
      <ul class="header-sub-menu">
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "sub-menu-link-product first-link sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
      </ul>
      </div>  
    </li>

    <div id="aide-popup" class="white-popup mfp-hide">
      <div class="popup-content">
      <p class="parlez-nous">Parlez nous ! (on est sympas et serviables)</p>
      <a class="help-button-chat" href="">Chat (suivez la bulle rouge)</a>
      <a class="help-button-email" href="mailto:bonjour@nationale-7.fr">bonjour@nationale-7.fr</a>
      <a class="help-button-phone" href="tel:0176390284">01 76 39 02 84</a>
      <p class="horaires-popup">Nous sommes ouverts du lundi au samedi de 9h à 20h !</p>
      </div>
    </div>
  </ul>

  <ul id="mobile-menu">
    <li>POURQUOI NATIONALE 7 ?
      <ul>
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "menu-link-mobile" %></li>
      </ul>
    </li>
    <li><%= link_to 'ACHETER', acheter_voiture_occasion_path, class: "menu-link-mobile" %></li>
    <li><%= link_to 'VENDRE', vendre_voiture_occasion_path, class: "menu-link-mobile" %></li>  
    <li class="besoin-aide"><a href="#aide-popup" class="open-popup-link menu-link-mobile">BESOIN D'AIDE ?</a></li>  
    <li class=""><a href="tel:0176390284" class="header-number-product">01 76 39 02 84</a></li>
  </ul>  


</header>


<div class="grey-title-wrap">
  <h1 class="expertise-title">L'EXPERTISE NATIONALE 7</h1>
  <h3 class="expertise-subtitle">L'expérience au profit de votre voiture</h3>
</div>


<div class="expertise-explanation-wrap">
  <p>Passage nécessaire pour estimer au mieux votre voiture, l’expertise Nationale 7 comprend la visite d'un de nos experts pendant une heure pour inspecter votre voiture dans ses moindres détails.</p>
  <p>Suivant un process éprouvé, notre expert vérifie :</p>
</div>

<div class="expertise-pictos">
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-75-points.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>75</span><span>points</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-carrosserie-interieur.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Carrosserie</span><span>et intérieur</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-mecanique.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Mécanique</span><span>et chassis</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-historique-entretien.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Historique</span><span>et entretien</span></p>
  </div>
  <div class="expertise-picto-wrap last-expert-wrap">
    <%= image_tag('expertise-test-conduite.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Test</span><span>de conduite</span></p>
  </div>
</div>

<div class="expertise-experveo-wrap">
  <%= image_tag('expertise-nationale-7.jpg', class: "fake-expertise-img") %>
  <div class="experveo-presentation">
    <p class="experveo-presentation-title">Qui sont ces experts ?</p>
    <p class="experveo-presentation-copy"><span>Aujourd'hui nous travaillons main dans la main avec Experveo, filiale de BCA expertise, un leader du domaine depuis 1995.</span><span>Avec un réseau de 600 experts agréés par le Ministère de l'intérieur, ils interviennent chez vous en moins de 48h. Si tout est conforme, la qualité de votre voiture est certifiée Nationale 7 !</span></p>
    <%= image_tag('certifie-experveo-green.jpg', class: "experveo-presentation-img") %>
  </div>  
</div>

<div class="expertise-white-separator"></div>

app/views/welcome/expertisen7.html.erb
<header class="header-product">
  <div class="logo-product">
    <%= link_to image_tag('logo-blue.png'), root_path, class: "logo-product" %>
  </div>


  <ul class="menu align-right homepage-nav-bar"> 
    <li class="phone-number-header-product header-link-product"><a href="tel:0176390284" class="header-number-product">01 76 39 02 84</a></li>

    <li class="besoin-aide header-link-product"><a href="#aide-popup" class="open-popup-link menu-link-product sliding-middle-out sliding-blue">Besoin d'aide ?</a></li>  
    
    <li class="header-link-product"><%= link_to 'Vendre', vendre_path, class: "menu-link-product sliding-middle-out sliding-blue" %></li>  
    <li class="header-link-product"><%= link_to 'Acheter', acheter_path, class: "menu-link-product sliding-middle-out sliding-blue" %></li>
    <li class="header-link-product wrapper pourquoi-n7 sliding-blue">Pourquoi Nationale 7 ?
      <div class="sub-menu-homepage">
      <ul class="header-sub-menu">
        <li><%= link_to 'Comment ça marche ?', commentcamarche_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'Les prix N7', prixn7_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'L\'expertise N7', expertisen7_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'FAQ', faq_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
        <li><%= link_to 'A propos', apropos_path, class: "sub-menu-link-product sliding-middle-out sliding-blue" %></li>
      </ul>

      </div>  
    </li>

    <div id="aide-popup" class="white-popup mfp-hide">
      <div class="popup-content">
      <p class="parlez-nous">Parlez nous ! (on est sympas et serviables)</p>
      <a class="help-button-chat" href="">Chat (suivez la bulle rouge)</a>
      <a class="help-button-email" href="mailto:bonjour@nationale7.co">bonjour@nationale7.co</a>
      <a class="help-button-phone" href="tel:0176390284">01 76 39 02 84</a>
      </div>
    </div>
      
  </ul>

</header>


<div class="grey-title-wrap">
  <h1 class="expertise-title">L'EXPERTISE NATIONALE 7</h1>
  <h3 class="expertise-subtitle">L'expérience au profite de votre voiture</h3>
</div>


<div class="expertise-explanation-wrap">
  <p>Passage nécessaire pour estimer au mieux votre voiture, l’expertise Nationale 7 comprend la visite d'un de nos experts pendant une heure pour inspecter votre voiture dans ses moindres détails.</p>
  <p>Suivant un process éprouvé, notre expert vérifie :</p>
</div>

<div class="expertise-pictos">
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-75-points.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>75</span><span>points</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-carrosserie-interieur.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Carrosserie</span><span>et intérieur</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-mecanique.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Mécanique</span><span>et chassis</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-historique-entretien.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Historique</span><span>et entretien</span></p>
  </div>
  <div class="expertise-picto-wrap">
    <%= image_tag('expertise-test-conduite.jpg', class: "expertise-picto-img") %>
    <p class="expertise-p"><span>Test</span><span>de conduite</span></p>
  </div>
</div>

<div class="expertise-experveo-wrap">
  <%= image_tag('fake-expertise.jpg', class: "fake-expertise-img") %>
  <div class="experveo-presentation">
    <p class="experveo-presentation-title">Qui sont ces experts ?</p>
    <p class="experveo-presentation-copy"><span>Aujourd'hui nous travaillons main dans la main avec Experveo, filiale de BCA expertise, un leader du domaine depuis 1995.</span><span>Avec un réseau de 600 experts agréés par le Ministère de l'intérieur, ils interviennent chez vous en moins de 48h. Si tout est conforme, la qualité de votre voiture est certifiée Nationale 7 !</span></p>
    <%= image_tag('certifie-experveo-green.jpg', class: "experveo-presentation-img") %>
  </div>  
</div>

<div class="expertise-white-separator"></div>

app/views/welcome/les_prix_nationale_7.html.erb
<header class="header-prix">
  <div class="logo-homepage">
    <%= link_to image_tag('logo-homepage.png'), root_path, class: "logo-homepage" %>
  </div>


  <ul class="menu align-right homepage-nav-bar"> 
    <li class="phone-number-header-homepage header-link-homepage"><a href="tel:0176390284" class="header-number-homepage">01 76 39 02 84</a></li>

    <li class="besoin-aide header-link-homepage"><a href="#aide-popup" class="open-popup-link menu-link-homepage sliding-middle-out sliding-white">Besoin d'aide ?</a></li>  
    
    <li class="header-link-homepage"><%= link_to 'Vendre', vendre_voiture_occasion_path, class: "menu-link-homepage sliding-middle-out sliding-white" %></li>  
    <li class="header-link-homepage"><%= link_to 'Acheter', acheter_voiture_occasion_path, class: "menu-link-homepage sliding-middle-out sliding-white" %></li>
    <li class="header-link-homepage wrapper pourquoi-n7 sliding-white">Pourquoi Nationale 7 ?
      <div class="sub-menu-homepage">
      <ul class="header-sub-menu">
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "sub-menu-link-homepage first-link sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
      </ul>

      </div>  
    </li>

    <div id="aide-popup" class="white-popup mfp-hide">
      <div class="popup-content">
      <p class="parlez-nous">Parlez nous ! (on est sympas et serviables)</p>
      <a class="help-button-chat" href="">Chat (suivez la bulle rouge)</a>
      <a class="help-button-email" href="mailto:bonjour@nationale-7.fr">bonjour@nationale-7.fr</a>
      <a class="help-button-phone" href="tel:0176390284">01 76 39 02 84</a>
      <p class="horaires-popup">Nous sommes ouverts du lundi au samedi de 9h à 20h !</p>
      </div>
    </div>
  </ul>

  <ul id="mobile-menu">
    <li>POURQUOI NATIONALE 7 ?
      <ul>
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "menu-link-mobile" %></li>
      </ul>
    </li>
    <li><%= link_to 'ACHETER', acheter_voiture_occasion_path, class: "menu-link-mobile" %></li>
    <li><%= link_to 'VENDRE', vendre_voiture_occasion_path, class: "menu-link-mobile" %></li>  
    <li class="besoin-aide"><a href="#aide-popup" class="open-popup-link menu-link-mobile">BESOIN D'AIDE ?</a></li>  
    <li class=""><a href="tel:0176390284" class="header-number-product">01 76 39 02 84</a></li>
  </ul>  

  <div class="prix-tagline-wrap">
    <h1 class="prix-h1-tagline">LES PRIX NATIONALE 7</h1>
    <h2 class="prix-h2-tagline">Plus d'argent aux vendeurs et des acheteurs qui paient moins cher !</h2>
  </div>

</header>

<div class="prix-comparaison-wrap">
	<p class="comparaison-p"><span>Les vendeurs obtiennent 20% de plus pour la vente de leur voiture.</span><span>Quant aux acheteurs, ils paient 10% de moins qu'en concession.</span><span>Comment faire pour que tout le monde soit gagnant dans la transaction ?</span><span>Voici comment ça marche chez Nationale 7 !</span></p>

	<div class="comparaison-wrap">
		<p class="a-vendre">À vendre</p>
		<%= image_tag "profil-ds4.jpg", class: "profil-ds4" %>
		<div class="comparaison-image-wrap">
			<div class="comparaison-header">
			  <div class="comparaison-header-1">Concessionnaire</div>
			  <div class="comparaison-header-2"><%= image_tag "logo-blue.png", class: "logo-comparaison" %>
				</div>
				<!-- <span> -->
			  	<div class="comparaison-header-3">Prix 12 000 €</div>
			  	<div class="comparaison-header-4">Prix 10 800 €</div>
			  <!-- </span> -->
			</div>
			<div class="revenu-concessionnaire ">Revenus concessionnaire 3 600 €</div>
			<div class="revenu-n7">Revenus N7 &nbsp 600 €</div>
			<div class="marge-concessionnaire">Marge vendeur 8 400 €</div>
			<div class="marge-n7">Marge vendeur 10 200 €</div>
			<%= image_tag "prix-comparaison.png", class: "prix-comparaison-img" %>
		</div>
	</div>
</div>

<div class="prix-evaluation-wrap">
	<p class="prix-evaluation-titre">Comment fixons-nous le prix de vente ?</p>
	<%= image_tag "prix-evaluation.png", class: "prix-evaluation-img" %>
	<%= image_tag "prix-evaluation-mobile.png", class: "prix-evaluation-mobile" %>
	<p class="prix-evaluation-p">Définir le bon prix pour votre véhicule n’est pas simple : c’est la raison pour laquelle nous avons développé nos propres outils, qui analysent en temps réel l’offre de véhicules comparables.</p>
	<p class="prix-evaluation-p">Basés sur l’intégralité des annonces réelles, ces outils nous permettent de définir un prix de vente au plus près de la réalité du marché : un concentré de technique à votre service pour s’assurer que nous définissons ensemble le juste prix !</p>
	<p class="prix-evaluation-p evaluation-last-p">Le prix définitif de votre véhicule est ensuite validé lors de l’inspection complète de la voiture en fonction de l’état précis du véhicule.</p>
	
</div>

	<div class="prix-options-wrap">
		<p class="prix-options-titre"><span>Le secret :</span><span> un coût minimal, un service maximal</span></p>
		
		<div class="option-div petites-annonces">
		<p class="option-sous-titre">Petites annonces</p>
		<%= image_tag "prix-annonces.png", class: "option-img" %>
		<p class="option-p-1"><span>Tout faire soi-même,</span><span>sans être sûr de faire la bonne affaire.</span></p>
		<p class="option-p-2">Toujours difficile d’éplucher les annonces pendant des heures, faire semblant d’inspecter la voiture puis se lancer dans une conversation rarement agréable.</p>
		</div>
		<div class="option-div concessionnaire">
		<p class="option-sous-titre">Concessionnaire</p>
		<%= image_tag "prix-usine.png", class: "option-img" %>
		<p class="option-p-1"><span>Un service traditionnel,</span><span> à prix d'or.</span></p>
		<p class="option-p-2">Un professionnel de l’automobile prend en moyenne 30 % de commission sur la vente d’une auto d’occasion. C’est le minimum nécessaire pour assumer ses coûts très élevés : showroom, vendeurs, trésorerie, assurance etc.</p>
	</div>
	<div style="clear:both;"></div>
</div>

<div class="n7-option">
	<div class="arrow-down"></div>
	<%= image_tag "logo-homepage.png", class: "option-n7-logo" %>
	<%= image_tag "prix-ampoule.png", class: "option-n7-img" %>
	<p class="option-n7-titre">La solution : un service maxi sans les coûts.</p>
	<div class="option-n7-p">​​​​​​​Nationale 7 ne prend que 5% pour vendre votre voiture, sans que vous n’ayez à sortir de chez vous ! Nos coûts super légers et super flexibles nous permettent de tout offrir : estimation, inspection, visite virtuelle, livraison, garantie, avec sourire et bonne humeur !</div>
</div>

<div class="prix-cta">
	<p class="prix-cta-titre">Ça vous intéresse ?</p>
	
	<%= link_to 'Ça m\'intéresse d\'acheter avec N7', acheter_voiture_occasion_path, class: "prix-button prix-acheter" %>
	<%= link_to 'Ça m\'intéresse de vendre avec N7', vendre_voiture_occasion_path, class: "prix-button prix-vendre" %>

	<%= link_to 'Acheter avec N7', acheter_voiture_occasion_path, class: "prix-button-mobile prix-acheter-mobile" %>
	<%= link_to 'Vendre avec N7', vendre_voiture_occasion_path, class: "prix-button-mobile prix-vendre-mobile" %>

</div>