config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'welcome#index'
  
  #Cars controller
  get '/acheter-voiture-occasion', to: 'cars#acheter_voiture_occasion', as: 'acheter_voiture_occasion'  
  get '/vendre-voiture-occasion', to: 'cars#vendre_voiture_occasion', as: 'vendre_voiture_occasion'
  resources 'cars', :path => '/acheter-voiture-occasion'

  # Welcome controller
  get '/a-propos-de-nationale-7', to: 'welcome#a_propos_de_nationale_7', as: 'a_propos_de_nationale_7'
  get '/foire-aux-questions', to: 'welcome#foire_aux_questions', as: 'foire_aux_questions'
  get '/comment-ca-marche', to: 'welcome#comment_ca_marche', as: 'comment_ca_marche'
  get '/les-prix-nationale-7', to: 'welcome#les_prix_nationale_7', as: 'les_prix_nationale_7'
  get '/expertise-nationale-7', to: 'welcome#expertise_nationale_7', as: 'expertise_nationale_7'
  get '/conditions-generales-de-vente', to: 'welcome#conditions_generales_de_vente', as: 'conditions_generales_de_vente'
  get '/mentions-legales', to: 'welcome#mentions_legales', as: 'mentions_legales'


  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts
  match '/evaluations', to: 'evaluations#new', via: 'get'
  resources :evaluations


  resources 'acheteurs', :path => "/rechercher-voiture-occasion"
  resources 'sold', :path => "/voitures-occasion-vendues"
  resources 'annonces'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/nationale7v1/sitemaps/sitemap.xml.gz")

  #Footer routes
  get '/acheter-mini-occasion', to: 'cars#acheter_mini_occasion', as: 'acheter_mini_occasion'
  get '/acheter-diesel-occasion', to: 'cars#acheter_diesel_occasion', as: 'acheter_diesel_occasion'



end

app/models/car.rb
class Car < ActiveRecord::Base
  extend FriendlyId
  friendly_id :car_url, use: :slugged

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => %w[
                sorted_by
                with_marque
                with_energie
                with_prix_n7
              ]

  has_many :car_clients
  has_many :photos
  has_many :car_options

  def car_url
    "#{marque} #{modele} #{annee} #{motorisation} #{finition} #{reference_interne}"
  end


  def to_s
  "#{reference_interne} - #{marque} #{modele} - #{annee}"
  end

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("cars.created_at #{ direction }")
    when /^prix_n7_/
      order("cars.prix_n7 #{ direction }")
    when /^annee_/
      order("cars.annee #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }


  scope :with_marque, lambda { |marque|
    where(marque: [marque])
  }

  scope :with_energie, lambda { |energie|
    where(energie: [energie])
  }  

  scope :with_prix_n7, lambda { |prix_n7|
    where('cars.prix_n7 < ?', prix_n7)
  }  

  def self.options_for_sorted_by
    [
      ['Trier par', 'created_at_desc'],
      ['Prix croissant', 'prix_n7_asc'],
      ['Prix décroissant', 'prix_n7_desc'],
      ['Année croissant', 'annee_asc'],
      ['Année décroissante', 'annee_desc']
    ]
  end

  def self.options_for_select_marque
    order('marque').map { |e| [e.marque] }.uniq
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  def acheter_voiture_occasion
    
    prepare_meta_tags(
      title: "Acheter sa voiture d'occasion l'esprit léger",
      description: "Les voitures Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Acheter sa voiture d'occasion l'esprit léger grâce à Nationale 7.",
      description: "Les voitures Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg"
    }

    @filterrific = initialize_filterrific(
      Car.where(statut: 'Actif'),
      params[:filterrific],
      :select_options => {
        sorted_by: Car.where(statut: 'Actif').options_for_sorted_by,
        with_marque: Car.where(statut: 'Actif').options_for_select_marque,
        with_energie: ['Diesel', 'Essence'], 
        with_prix_n7: [
          ['Moins de 5 000 €', 5000], 
          ['Moins de 10 000 €', 10000], 
          ['Moins de 15 000 €', 15000], 
          ['Moins de 20 000 €', 20000], 
          ['Moins de 25 000 €', 25000], 
          ['Moins de 30 000 €', 30000],  
          ['Moins de 40 000 €', 40000], 
          ['Moins de 50 000 €', 50000], 
        ]
      },
      :persistence_id => false,
    ) or return 
    @cars = @filterrific.find.page(params[:page])
    @profile_photos = Photo.where(car_id: @cars.map(&:id)).where(description: 'Profile')

    respond_to do |format|
      format.html
      format.js
    end

  end

  def vendre_voiture_occasion
    
    prepare_meta_tags(
      title: "Vendre sa voiture et économiser des milliers d'euros",
      description: "Vendez votre voiture avec Nationale 7 et économisez des milliers d'euros par rapport à un concessionnaire. Expertise, garantie, paiement et paperasse : on s'en occupe !",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Vendre+voiture+occasion.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Vendre sa voiture d'occasion et économiser des milliers d'euros grâce à Nationale 7.",
      description: "Vendez votre voiture avec Nationale 7 et économisez des milliers d'euros par rapport à un concessionnaire. Expertise, garantie, paiement et paperasse : on s'en occupe !",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Vendre+voiture+occasion.jpg"
    }

    @evaluation = Evaluation.new
  end

  def show
    @contact = Contact.new
    @car = Car.friendly.find(params[:id])
    @caroptions = CarOption.where(car_id: @car.id)
    @inspector = Inspector.where(id: @car.inspector_id).first
    @options = Option.where(id: @caroptions.map(&:option_id))
    @photos = Photo.where(car_id: @car.id).order(created_at: :asc)
    
    prepare_meta_tags(
      title: "Saisissez cette " + @car.marque.to_s + " " +  @car.modele.to_s + "de " + @car.annee.to_s,
      description: @car.commentaire_general,
      image: @photos.second.picture_url,
      reverse: true
    )

    set_meta_tags og: {
      title: "Saisissez cette " + @car.marque.to_s + " " +  @car.modele.to_s + " de " + @car.annee.to_s + " inspectée et garantie",
      description: @car.commentaire_general,
      image: @photos.second.picture_url
    }

  end



  def acheter_mini_occasion
    
    prepare_meta_tags(
      title: "Acheter sa Mini d'occasion l'esprit léger",
      description: "Les Mini Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Acheter sa Mini d'occasion l'esprit léger grâce à Nationale 7.",
      description: "Les Mini Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg"
    }

    @filterrific = initialize_filterrific(
      Car.where(statut: 'Actif'),
      params[:filterrific],
      :select_options => {
        sorted_by: Car.where(statut: 'Actif').options_for_sorted_by,
        with_marque: Car.where(statut: 'Actif').options_for_select_marque,
        with_energie: ['Diesel', 'Essence'], 
        with_prix_n7: [
          ['Moins de 5 000 €', 5000], 
          ['Moins de 10 000 €', 10000], 
          ['Moins de 15 000 €', 15000], 
          ['Moins de 20 000 €', 20000], 
          ['Moins de 25 000 €', 25000], 
          ['Moins de 30 000 €', 30000],  
          ['Moins de 40 000 €', 40000], 
          ['Moins de 50 000 €', 50000], 
        ]
      },
      :persistence_id => false,
      default_filter_params: { with_marque: 'Mini'},
    ) or return 
    @cars = @filterrific.find.page(params[:page])
    @profile_photos = Photo.where(car_id: @cars.map(&:id)).where(description: 'Profile')

    respond_to do |format|
      # redirect_to action: :acheter_voiture_occasion
      format.html
      format.js
    end

  end

  def acheter_diesel_occasion
    
    prepare_meta_tags(
      title: "Acheter sa voiture diesel d'occasion l'esprit léger",
      description: "Les voitures Diesel Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg",
      reverse: true
    )

    set_meta_tags og: {
      title: "Acheter sa voiture diesel d'occasion l'esprit léger",
      description: "Les voitures Diesel Nationale 7 sont inspectées 75 points, garanties 6 mois et au meilleur prix. N7 s'occupe gère aussi la paperasse et la sécurisation du paiement.",
      image: "https://s3-eu-west-1.amazonaws.com/nationale7v1/Website+assets/Nationale+7+-+Acheter+voiture+occasion.jpg"
    }

    @filterrific = initialize_filterrific(
      Car.where(statut: 'Actif'),
      params[:filterrific],
      :select_options => {
        sorted_by: Car.where(statut: 'Actif').options_for_sorted_by,
        with_marque: Car.where(statut: 'Actif').options_for_select_marque,
        with_energie: ['Diesel', 'Essence'], 
        with_prix_n7: [
          ['Moins de 5 000 €', 5000], 
          ['Moins de 10 000 €', 10000], 
          ['Moins de 15 000 €', 15000], 
          ['Moins de 20 000 €', 20000], 
          ['Moins de 25 000 €', 25000], 
          ['Moins de 30 000 €', 30000],  
          ['Moins de 40 000 €', 40000], 
          ['Moins de 50 000 €', 50000], 
        ]
      },
      :persistence_id => false,
      default_filter_params: { with_energie: 'Diesel'},
    ) or return 
    @cars = @filterrific.find.page(params[:page])
    @profile_photos = Photo.where(car_id: @cars.map(&:id)).where(description: 'Profile')

    respond_to do |format|
      format.html
      format.js
    end

  end


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_list.html.erb
<div class="row page-acheter small-up-1 large-up-3" id="filterrific_results">
  <% @cars.each do |car| %>

  <script> 
    // This js snippet was put in erb because I couldn't figure out how to pass ruby variables in the js file
    $(document).ready(function(){

      $(".extra-info-layer").hide();

      $(".car-image-<%= car.id %>").mouseover(function () {
          $(".car-extra-info<%= car.id %>").show("fast");
      });

      $(".car-image-<%= car.id %>").mouseleave(function () {
        $(".car-extra-info<%= car.id %>").hide("fast");
      });
    });
  </script>

  <div class="column page-acheter carItem<%= car.id %>">
  	<div class="picture-extras page-acheter">
      <div class="car-image-<%= car.id %>">
    		<%= link_to image_tag( @profile_photos.where(car_id: car.id).first.picture_url, :class => "car-image" ), { action: 'show', controller: 'cars',  id: car.slug } %>
      </div>
    <div style="position: relative; height: 0">
  		<div class="car-extra-info<%= car.id %> extra-info-layer">
  			<p class="engine-version"><%= car.motorisation %> <%= car.finition %> </p>
  			<p class="mileage"> <%= number_with_delimiter(car.kilometrage, :delimiter => ' ') %> Km</p>
  		</div>
    </div>


  	</div>
    <p class="derniere-voiture-name">
      <%= car.marque %> <%= car.modele %> <%= car.annee %> 
    </p> </br>
    <p class="derniere-voiture-prix">
      <%= number_with_delimiter(car.prix_n7, :delimiter => ' ') %> €
    </p>
  </div>
  <% end %>
</div>

app/views/cars/_service_acheteur.html.erb
<div class="service-acheteur">

  <h2 class="recherche-title"><span>À LA RECHERCHE D'UNE VOITURE</span><span> EN PARTICULIER ?</span></h2>

  <%= link_to(raw('<i class="fa fa-bell fa-lg" aria-hidden="true"></i>&nbsp Je crée une alerte !'), acheteurs_path, class: "alertes-bouton-grand" )%>

</div>

app/views/cars/acheter.js.erb
<% js = escape_javascript(
  render(partial: 'cars/list', locals: { cars: @cars })
) %>

$('#filterrific_results').html('<%= js %>');

app/views/cars/acheter_diesel_occasion.html.erb
<%= render(partial: 'cars/white_header') %>
<%= render(partial: 'cars/search_filters') %>
<%= render(partial: 'cars/list', locals: { cars: @cars }) %>
<%= render(partial: 'cars/service_acheteur') %>

app/views/cars/acheter_mini_occasion.js.erb
<% js = escape_javascript(
  render(partial: 'cars/list', locals: { cars: @cars })
) %>

$('#filterrific_results').html('<%= js %>');

app/views/cars/acheter_voiture_occasion.html.erb
<%= render(partial: 'cars/white_header') %>
<%= render(partial: 'cars/search_filters') %>
<%= render(partial: 'cars/list', locals: { cars: @cars }) %>
<%= render(partial: 'cars/service_acheteur') %>

app/views/cars/acheter_voiture_occasion.js.erb
<% js = escape_javascript(
  render(partial: 'cars/list', locals: { cars: @cars })
) %>

$('#filterrific_results').html('<%= js %>');

app/views/cars/acheter_voiture_occasion_certifiee_garantie.js.erb
<% js = escape_javascript(
  render(partial: 'cars/list', locals: { cars: @cars })
) %>

$('#filterrific_results').html('<%= js %>');

app/views/cars/vendre_voiture_occasion.html.erb
<div>
  <% flash.each do |key, value| %>
    <% if flash[:alert] %>
      <div class="alert-message">
        <a href="#" data-dismiss="alert" class="alert-dismiss">×</a>
          <%= value %>
      </div>    
    <% else %>
      <div class="notice-message">
        <a href="#" data-dismiss="alert" class="alert-dismiss">×</a>
          <%= value %>
      </div>
    <% end %>
  <% end %>
</div>

<header class="header-vendre">
  <div class="logo-homepage">
    <%= link_to image_tag('logo-homepage.png'), root_path, class: "logo-homepage" %>
  </div>


  <ul class="menu align-right homepage-nav-bar"> 
    <li class="phone-number-header-homepage header-link-homepage"><a href="tel:0176390284" class="header-number-homepage">01 76 39 02 84</a></li>

    <li class="besoin-aide header-link-homepage"><a href="#aide-popup" class="open-popup-link menu-link-homepage sliding-middle-out sliding-white">Besoin d'aide ?</a></li>  
    
    <li class="header-link-homepage"><%= link_to 'Vendre', vendre_voiture_occasion_path, class: "menu-link-homepage sliding-middle-out sliding-white" %></li>  
    <li class="header-link-homepage"><%= link_to 'Acheter', acheter_voiture_occasion_path, class: "menu-link-homepage sliding-middle-out sliding-white" %></li>
    <li class="header-link-homepage wrapper pourquoi-n7 sliding-white">Pourquoi Nationale 7 ?
      <div class="sub-menu-homepage">
      <ul class="header-sub-menu">
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "sub-menu-link-homepage first-link sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "sub-menu-link-homepage sliding-middle-out sliding-black" %></li>
      </ul>

      </div>  
    </li>

    <div id="aide-popup" class="white-popup mfp-hide">
      <div class="popup-content">
      <p class="parlez-nous">Parlez nous ! (on est sympas et serviables)</p>
      <a class="help-button-chat" href="">Chat (suivez la bulle rouge)</a>
      <a class="help-button-email" href="mailto:bonjour@nationale-7.fr">bonjour@nationale-7.fr</a>
      <a class="help-button-phone" href="tel:0176390284">01 76 39 02 84</a>
      <p class="horaires-popup">Nous sommes ouverts du lundi au samedi de 9h à 20h !</p>
      </div>
    </div>
  </ul>

  <ul id="mobile-menu">
    <li>POURQUOI NATIONALE 7 ?
      <ul>
        <li><%= link_to 'Comment ça marche ?', comment_ca_marche_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Les prix N7', les_prix_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'L\'expertise N7', expertise_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'FAQ', foire_aux_questions_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'À propos', a_propos_de_nationale_7_path, class: "menu-link-mobile" %></li>
        <li><%= link_to 'Nos voitures vendues', { action: 'index', controller: 'sold'}, class: "menu-link-mobile" %></li>
      </ul>
    </li>
    <li><%= link_to 'ACHETER', acheter_voiture_occasion_path, class: "menu-link-mobile" %></li>
    <li><%= link_to 'VENDRE', vendre_voiture_occasion_path, class: "menu-link-mobile" %></li>  
    <li class="besoin-aide"><a href="#aide-popup" class="open-popup-link menu-link-mobile">BESOIN D'AIDE ?</a></li>  
    <li class=""><a href="tel:0176390284" class="header-number-product">01 76 39 02 84</a></li>
  </ul>  

  <div class="vendre-tagline-wrap">
    <h1 class="vendre-h1-tagline">Vendez votre voiture, <span>économisez des milliers d'euros, sans bouger de chez vous !</span></h1>
    <h2 class="vendre-h2-tagline"><span>Commençons par une évaluation gratuite de votre véhicule !</span><span>Soumettez le formulaire ci-dessous pour qu'un de nos experts vous rappelle dans la journée.</span></h2>
  </div>

</header>

    <div class="mascotte-vendre-div">
      <%= image_tag('mascotte-footer.png', class: "mascotte-vendre hvr-buzz-out") %>
    </div>

    <div class="sans-engagement">
      <p><strong><span>Sans engagement,</span>
      <span>on vous rappelle immédiatement !</span></p></strong>
    </div>


    <div class="vendre-form">

      <%= simple_form_for @evaluation, :html => {:class => 'form-horizontal' } do |f| %>
        <%= f.input :nom, :label => 'Nom et prénom', :required => false, wrapper_html: { class: 'email-field evaluation-input' } %>
        <%= f.input :email, :label => 'Email', :required => false, wrapper_html: { class: 'evaluation-input' } %>
        <%= f.input :phone_number, :label => 'Numéro de téléphone', :required => false, wrapper_html: { class: 'evaluation-input' } %> 
        <%= f.input :code_postal, :label => 'Code postal', :required => false, wrapper_html: { class: 'evaluation-input' } %> 
        <%= label_tag :'Description de la voiture :', nil, :class => "description-label string evaluation-input" %>
        <%= f.input :description, :label => 'marque, modèle, année, motorisation, finition, kilométrage', :required => false, wrapper_html: { class: 'evaluation-input' } %>
        <div class="form-aide">Rassurez-vous si vous n'avez pas toute l'information, <span>nous vous aiderons à la trouver !</span></div>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div class="evaluation-button">
        <%= f.button :submit, 'Envoyer à l\'équipe N7', :class=> "evaluation-form-button" %>
      </div>
       <% end %>
    </div>

    <div class="vendre-bottom-explanation">
      
      <div class="vendre-bottom-row">
        <p class="vendre-bottom-title">PLACE À LA SIMPLICITÉ</p>

        <div class="vendre-bottom-section-wrap">

          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-rendez-vous.jpg', class: "vendre-picto-img") %>
            </div>
            <p class="vendre-bottom-copy"><span>Prenez rendez-vous pour</span><span> l'inspection, où et quand cela</span><span> vous arrange, gratuitement.</span></p>
          </div>
          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-meilleur-prix.jpg', class: "vendre-picto-img") %>
            </div>
            <p class="vendre-bottom-copy"><span>Nous vous donnerons un prix final,</span><span>avant la mise-en-marché.</span>Garanti plus élevé que chez un concessionnaire.</p>
          </div>
          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-utiliser-voiture.jpg', class: "vendre-picto-img") %>
            </div>  
            <p class="vendre-bottom-copy"><span>Continuez d'utiliser votre auto</span><span>le temps que l'on trouve votre</span><span>futur acheteur.</span></p>
          </div>
        </div>
      </div>

      <div class="vendre-bottom-row">
        <p class="vendre-bottom-title">C'EST L'HEURE DE SE DIRE AU-REVOIR</p>

        <div class="vendre-bottom-section-wrap">
          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-acheteur.jpg', class: "vendre-picto-img") %>
            </div>
            <p class="vendre-bottom-copy"><span>Un acheteur s'est</span><span>manifesté, nous venons chez</span><span>vous enlever la voiture.</span></p>
          </div>
          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-paperasse.jpg', class: "vendre-picto-img") %>
            </div>
            <p class="vendre-bottom-copy"><span>La paperasse sera prête, il n'y</span><span>aura plus qu'à signer</span></p>
          </div>
          <div class="vendre-bottom-section">
            <div class="vendre-picto-wrap">
              <%= image_tag('vendre-paiement-securise.jpg', class: "vendre-picto-img") %>
            </div>
            <p class="vendre-bottom-copy"><span>Nous sécurisons le paiement</span><span>grâce à nos partenaires</span><span>Lemonway et BNP Paribas.</span></p>
          </div>
        </div>
      </div>
    </div>
    <div class="vendre-bottom-white">
    </div>