config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'welcome#index'
  
  #Cars controller
  get '/acheter-voiture-occasion', to: 'cars#acheter_voiture_occasion', as: 'acheter_voiture_occasion'  
  get '/vendre-voiture-occasion', to: 'cars#vendre_voiture_occasion', as: 'vendre_voiture_occasion'
  resources 'cars', :path => '/acheter-voiture-occasion'

  # Welcome controller
  get '/a-propos-de-nationale-7', to: 'welcome#a_propos_de_nationale_7', as: 'a_propos_de_nationale_7'
  get '/foire-aux-questions', to: 'welcome#foire_aux_questions', as: 'foire_aux_questions'
  get '/comment-ca-marche', to: 'welcome#comment_ca_marche', as: 'comment_ca_marche'
  get '/les-prix-nationale-7', to: 'welcome#les_prix_nationale_7', as: 'les_prix_nationale_7'
  get '/expertise-nationale-7', to: 'welcome#expertise_nationale_7', as: 'expertise_nationale_7'
  get '/conditions-generales-de-vente', to: 'welcome#conditions_generales_de_vente', as: 'conditions_generales_de_vente'
  get '/mentions-legales', to: 'welcome#mentions_legales', as: 'mentions_legales'


  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts
  match '/evaluations', to: 'evaluations#new', via: 'get'
  resources :evaluations


  resources 'acheteurs', :path => "/rechercher-voiture-occasion"
  resources 'sold', :path => "/voitures-occasion-vendues"
  resources 'annonces'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/nationale7v1/sitemaps/sitemap.xml.gz")

  #Footer routes
  get '/acheter-mini-occasion', to: 'cars#acheter_mini_occasion', as: 'acheter_mini_occasion'
  get '/acheter-diesel-occasion', to: 'cars#acheter_diesel_occasion', as: 'acheter_diesel_occasion'



end

app/models/acheteur.rb
class Acheteur < MailForm::Base
  attribute :type_1
  attribute :marque_1
  attribute :modele_1
  attribute :transmission_1
  attribute :carburant_1
  attribute :annee_min_1
  attribute :annee_max_1
  attribute :kilometrage_min_1
  attribute :kilometrage_max_1
  attribute :prix_min_1
  attribute :prix_max_1
  
  attribute :type_2
  attribute :marque_2
  attribute :modele_2
  attribute :transmission_2
  attribute :carburant_2
  attribute :annee_min_2
  attribute :annee_max_2
  attribute :kilometrage_min_2
  attribute :kilometrage_max_2
  attribute :prix_min_2
  attribute :prix_max_2

  attribute :type_3
  attribute :marque_3
  attribute :modele_3
  attribute :transmission_3
  attribute :carburant_3
  attribute :annee_min_3
  attribute :annee_max_3
  attribute :kilometrage_min_3
  attribute :kilometrage_max_3
  attribute :prix_min_3
  attribute :prix_max_3

  attribute :nom
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone_number
  attribute :code_postal
  attribute :nickname,  :captcha  => true
  attribute :details

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nouvelle alerte acheteur",
      :to => "gael@nationale-7.fr",
      :from => "gael@nationale-7.fr"
    }
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/car.rb
class Car < ActiveRecord::Base
  extend FriendlyId
  friendly_id :car_url, use: :slugged

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => %w[
                sorted_by
                with_marque
                with_energie
                with_prix_n7
              ]

  has_many :car_clients
  has_many :photos
  has_many :car_options

  def car_url
    "#{marque} #{modele} #{annee} #{motorisation} #{finition} #{reference_interne}"
  end


  def to_s
  "#{reference_interne} - #{marque} #{modele} - #{annee}"
  end

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("cars.created_at #{ direction }")
    when /^prix_n7_/
      order("cars.prix_n7 #{ direction }")
    when /^annee_/
      order("cars.annee #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }


  scope :with_marque, lambda { |marque|
    where(marque: [marque])
  }

  scope :with_energie, lambda { |energie|
    where(energie: [energie])
  }  

  scope :with_prix_n7, lambda { |prix_n7|
    where('cars.prix_n7 < ?', prix_n7)
  }  

  def self.options_for_sorted_by
    [
      ['Trier par', 'created_at_desc'],
      ['Prix croissant', 'prix_n7_asc'],
      ['Prix décroissant', 'prix_n7_desc'],
      ['Année croissant', 'annee_asc'],
      ['Année décroissante', 'annee_desc']
    ]
  end

  def self.options_for_select_marque
    order('marque').map { |e| [e.marque] }.uniq
  end

end

app/models/car_client.rb
class CarClient < ActiveRecord::Base
  belongs_to :client
  belongs_to :inspector
  belongs_to :car

  def to_s
  "#{id} - #{client} #{position}"
  end

end

app/models/car_option.rb
class CarOption < ActiveRecord::Base
  belongs_to :option
  belongs_to :car 
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :car_clients

  def to_s
  "#{id} - #{first_name} #{last_name} - #{city}"
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone_number
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :details

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "emmanuel@nationale-7.fr",
      :from => "gael@nationale-7.fr"
    }
  end
end

app/models/evaluation.rb
class Evaluation < MailForm::Base
  attribute :nom
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone_number
  attribute :description
  # attribute :modele
  # attribute :annee
  # attribute :motorisation
  # attribute :finition
  # attribute :kilometrage
  attribute :code_postal
  attribute :nickname,  :captcha  => true
  attribute :details

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nouvelle demande d'évaluation",
      :to => "emmanuel@nationale-7.fr",
      :from => "gael@nationale-7.fr"
    }
  end
end

app/models/inspector.rb
class Inspector < ActiveRecord::Base
  # has_many :voitures
  has_many :car_clients

  def to_s
    "#{id} - #{first_name} #{last_name} - #{location_city}"
  end

end

app/models/option.rb
class Option < ActiveRecord::Base
  has_many :car_options

  def to_s
    "#{id} #{description}"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :car
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/evaluation_helper.rb
module EvaluationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sold_helper.rb
module SoldHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="mascotte-div">
  <%= image_tag('mascotte-footer.png', class: "mascotte-footer hvr-buzz-out") %>
</div>

  <div class="footer-links">
    <%= link_to 'COMMENT ÇA MARCHE ?', comment_ca_marche_path, class: "footer-link" %>
    <%= link_to 'FAQ', foire_aux_questions_path, class: "footer-link" %>
    <%= link_to 'À PROPOS', a_propos_de_nationale_7_path, class: "footer-link" %>
    <%= link_to 'CONDITIONS GÉNÉRALES', conditions_generales_de_vente_path, class: "footer-link" %>
    <%= link_to 'MENTIONS LÉGALES', mentions_legales_path, class: "footer-link" %>
  </div>

  <div class="social-buttons">
    <a href="https://www.facebook.com/N7officiel/" target="_blank" class="fa fa-facebook fa-2x hvr-grow social-icon"></a>
    <a href="https://twitter.com/N7_officiel" target="_blank" class="fa fa-twitter fa-2x hvr-grow social-icon"></a>
    <a href="https://www.linkedin.com/company/nationale-7.fr" target="_blank" target="_blank" class="fa fa-linkedin fa-2x hvr-grow social-icon"></a>
  </div>

  <div class="corporate-details">
    <p>© Nationale 7 - 2016 - Tous droits réservés</p>
    <p class="corpo-p">Nationale 7 SAS - SIREN 820 295 558</p>
    <p class="corpo-p">TVA intracommunautaire FR 81 820295558</p>
    <p class="corpo-p">14 rue Soleillet, 75020 Paris</p>
    <%= image_tag("logo-lemonway-white.png", id:'lemonway-partner-logo' ) %>
    <p class="lemonway-partner-statement"><span>Partenaire de Lemon Way,</span><span> établissement de paiement</span><span> agréé par l’ACPR en France (CIB 16568).</span></p>

  </div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-site-verification" content="Frv3yJFq_D4bZdxyOOhrTYjJecyqBCTCHQkqPErWHz8" />
    <%= display_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick-theme.css"/>
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="//load.sumome.com/" data-sumo-site-id="5bd414215cea46151e23d9f8bd40ea2621581c56d40b3b27ae7902fb8fd60a51" async="async"></script><script src="//load.sumome.com/" data-sumo-site-id="5bd414215cea46151e23d9f8bd40ea2621581c56d40b3b27ae7902fb8fd60a51" async="async"></script>
  </head>

  <body>
    <div id="wrapper">

      <%= yield %>
      <%= render 'layouts/footer' %>
      <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
      <script>
        window.intercomSettings = {
          app_id: "cusnq9r8"
        };
      </script>
    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-78400700-1', 'auto');
      ga('send', 'pageview');

    </script>

  </body>
</html>

  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->